// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiEtl.Infrastructure.Persistence;

#nullable disable

namespace TaxiEtl.Infrastructure.Migrations
{
    [DbContext(typeof(TaxiEtlDbContext))]
    [Migration("20251116072113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiEtl.Domain.Entities.Trip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DOLocationId")
                        .HasColumnType("int")
                        .HasColumnName("DOLocationID");

                    b.Property<DateTime>("DropoffUtc")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("tpep_dropoff_datetime");

                    b.Property<decimal>("FareAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("fare_amount");

                    b.Property<int>("PULocationId")
                        .HasColumnType("int")
                        .HasColumnName("PULocationID");

                    b.Property<byte>("PassengerCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("passenger_count");

                    b.Property<DateTime>("PickupUtc")
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("tpep_pickup_datetime");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("store_and_fwd_flag");

                    b.Property<decimal>("TipAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tip_amount");

                    b.Property<int>("TravelTimeSeconds")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("TravelTimeSeconds")
                        .HasComputedColumnSql("DATEDIFF(SECOND, [tpep_pickup_datetime], [tpep_dropoff_datetime])", true);

                    b.Property<decimal>("TripDistance")
                        .HasColumnType("decimal(9,3)")
                        .HasColumnName("trip_distance");

                    b.HasKey("Id");

                    b.HasIndex("PULocationId")
                        .HasDatabaseName("IX_Trips_PULocation_TipAmount");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PULocationId"), new[] { "TipAmount" });

                    b.HasIndex("TravelTimeSeconds")
                        .HasDatabaseName("IX_Trips_TravelTimeSeconds");

                    b.HasIndex("TripDistance")
                        .HasDatabaseName("IX_Trips_TripDistance");

                    b.ToTable("Trips", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
