using TaxiEtl.Domain.ValueObjects;

namespace TaxiEtl.Domain.Entities
{
    /// <summary>
    /// Represents a single taxi trip with normalized, validated data ready
    /// to be persisted and queried in the analytics database.
    /// </summary>
    public class Trip
    {
        /// <summary>
        /// Parameterless constructor required by some ORMs (e.g. EF Core).
        /// Not intended for direct use in application code.
        /// </summary>
        private Trip()
        {
        }

        /// <summary>
        /// Creates a new <see cref="Trip"/> instance with the specified values.
        /// </summary>
        /// <param name="pickupUtc">
        /// Pickup time in UTC (or a <see cref="DateTime"/> that will be marked as UTC).
        /// </param>
        /// <param name="dropoffUtc">
        /// Dropoff time in UTC (or a <see cref="DateTime"/> that will be marked as UTC).
        /// Must be greater than or equal to <paramref name="pickupUtc"/>.
        /// </param>
        /// <param name="passengerCount">
        /// Number of passengers for this trip.
        /// </param>
        /// <param name="tripDistance">
        /// Distance of the trip. Must be non-negative.
        /// </param>
        /// <param name="storeAndFwdFlag">
        /// Store-and-forward flag indicating whether the trip record was stored
        /// and forwarded at a later time by the vehicle's device.
        /// </param>
        /// <param name="puLocationId">
        /// Pickup location identifier (PU location ID).
        /// </param>
        /// <param name="doLocationId">
        /// Dropoff location identifier (DO location ID).
        /// </param>
        /// <param name="fareAmount">
        /// Fare amount for the trip. Must be non-negative.
        /// </param>
        /// <param name="tipAmount">
        /// Tip amount for the trip. Must be non-negative.
        /// </param>
        /// <exception cref="ArgumentException">
        /// Thrown when <paramref name="dropoffUtc"/> is earlier than <paramref name="pickupUtc"/>.
        /// </exception>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when <paramref name="tripDistance"/>, <paramref name="fareAmount"/> or
        /// <paramref name="tipAmount"/> is negative.
        /// </exception>
        public Trip(
            DateTime pickupUtc,
            DateTime dropoffUtc,
            byte passengerCount,
            decimal tripDistance,
            StoreAndFwdFlag storeAndFwdFlag,
            int puLocationId,
            int doLocationId,
            decimal fareAmount,
            decimal tipAmount)
        {
            if (dropoffUtc < pickupUtc)
            {
                throw new ArgumentException(
                    "Dropoff time must be greater than or equal to pickup time.",
                    nameof(dropoffUtc));
            }

            if (tripDistance < 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(tripDistance),
                    "Trip distance cannot be negative.");
            }

            if (fareAmount < 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(fareAmount),
                    "Fare amount cannot be negative.");
            }

            if (tipAmount < 0)
            {
                throw new ArgumentOutOfRangeException(
                    nameof(tipAmount),
                    "Tip amount cannot be negative.");
            }

            PickupUtc = EnsureUtc(pickupUtc);
            DropoffUtc = EnsureUtc(dropoffUtc);
            PassengerCount = passengerCount;
            TripDistance = tripDistance;
            StoreAndFwdFlag = storeAndFwdFlag;
            PULocationId = puLocationId;
            DOLocationId = doLocationId;
            FareAmount = fareAmount;
            TipAmount = tipAmount;
        }

        /// <summary>
        /// Surrogate primary key of the trip record, typically generated by the database.
        /// </summary>
        public long Id { get; private set; }

        /// <summary>
        /// Pickup time of the trip in UTC.
        /// </summary>
        public DateTime PickupUtc { get; private set; }

        /// <summary>
        /// Dropoff time of the trip in UTC.
        /// </summary>
        public DateTime DropoffUtc { get; private set; }

        /// <summary>
        /// Number of passengers that took the trip.
        /// </summary>
        public byte PassengerCount { get; private set; }

        /// <summary>
        /// Distance travelled during the trip, in the units provided by the source system
        /// (typically miles or kilometers, depending on the dataset).
        /// </summary>
        public decimal TripDistance { get; private set; }

        /// <summary>
        /// Indicates whether the trip record was stored and forwarded at a later time
        /// by the vehicle's device (<see cref="StoreAndFwdFlag"/>).
        /// </summary>
        public StoreAndFwdFlag StoreAndFwdFlag { get; private set; }

        /// <summary>
        /// Pickup location identifier (PU location ID) used for spatial queries and aggregation.
        /// </summary>
        public int PULocationId { get; private set; }

        /// <summary>
        /// Dropoff location identifier (DO location ID) used for spatial queries and aggregation.
        /// </summary>
        public int DOLocationId { get; private set; }

        /// <summary>
        /// Total fare amount charged for the trip, excluding tip.
        /// </summary>
        public decimal FareAmount { get; private set; }

        /// <summary>
        /// Tip amount paid for the trip.
        /// </summary>
        public decimal TipAmount { get; private set; }

        /// <summary>
        /// Duration of the trip in seconds.
        /// </summary>
        /// <remarks>
        /// This property can be mapped to a computed column in the database
        /// (based on <see cref="PickupUtc"/> and <see cref="DropoffUtc"/>) or
        /// calculated in application code, depending on the persistence strategy.
        /// </remarks>
        public int TravelTimeSeconds { get; private set; }

        /// <summary>
        /// Ensures that the specified <see cref="DateTime"/> is marked as UTC without
        /// performing any time-zone conversion.
        /// </summary>
        /// <param name="value">The date and time value to normalize.</param>
        /// <returns>
        /// The same <see cref="DateTime"/> value with <see cref="DateTime.Kind"/> set to
        /// <see cref="DateTimeKind.Utc"/>.
        /// </returns>
        private static DateTime EnsureUtc(DateTime value)
        {
            if (value.Kind == DateTimeKind.Utc)
            {
                return value;
            }

            return DateTime.SpecifyKind(value, DateTimeKind.Utc);
        }
    }
}
